<a href="https://colab.research.google.com/github/JKDHEERAJSINGH/GENAI2025/blob/main/Numpy_class1_26_5_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list(),str(),tuple(),set(),dict()

([], '', (), set(), {})

In [ ]:
y=np.array([1,2,3,4,5])

In [ ]:
y

array([1, 2, 3, 4, 5])

In [ ]:
x=(14.8)

In [ ]:
type(x),type(y)

(float, numpy.ndarray)

In [ ]:
x/2

7.4

In [ ]:
y/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
x=[1,2,3,"data science"]

In [ ]:
x

[1, 2, 3, 'data science']

In [ ]:
a=[34444,66666,99]

In [ ]:
type(a)

list

In [ ]:
a[0]

34444

In [ ]:
a[2]

99

In [ ]:
type(x[3]),type(x[0]),type(x[2])

(str, int, int)

In [ ]:
y=np.array([1,2,3,4,5,6])

In [ ]:
y

array([1, 2, 3, 4, 5, 6])

In [ ]:
dheeraj="data science"
dheeraj_r=24
dheeraj_c="mca"

In [ ]:
dheeraj

'data science'

In [ ]:
dheeraj_r

24

In [ ]:
(y[0]),type(y[1]),type(y[2]),type(y[3])

(np.int64(1), numpy.int64, numpy.int64, numpy.int64)

In [ ]:
y=np.array([1,2,3,4,5,6,"data"])

In [ ]:
y[4],type(y[1]),type(y[2]),type(y[3])

(np.str_('5'), numpy.str_, numpy.str_, numpy.str_)

In [ ]:
y=(3,7,8)

In [ ]:
y[0]

3

In [ ]:
for r in range(1,10):
  print(np.random.randint(0,10))

5
9
4
2
4
1
4
1
0


In [ ]:
y[2]

8

In [ ]:
import numpy as np

In [ ]:
for r in range(0,10):
  print(np.random.randint(0,100))

65
74
5
77
33
42
54
36
12
38


In [ ]:
np.random.randint(1,100,(5,5))

array([[94, 95, 62, 30, 89],
       [68,  2, 91, 94, 11],
       [38, 96, 43, 77, 34],
       [21, 69, 56, 37, 45],
       [49, 27,  4,  6, 26]])

In [ ]:
data=np.random.randint(1,100,(3,3))

In [ ]:
data

array([[68, 99, 22],
       [58, 24, 26],
       [92, 14, 34]])

In [ ]:
data[1,1]      #r ,c

np.int64(24)

In [ ]:
data[0,2]

np.int64(22)

In [ ]:
data[0,1]

np.int64(99)

In [ ]:
data[1,2]

np.int64(26)

In [ ]:
data[0,0:2]

array([68, 99])

In [ ]:
data=np.random.randint(0,20,(5,5))

In [ ]:
data

array([[ 2, 19, 19,  9, 15],
       [11, 13,  4, 15,  5],
       [ 1,  1, 10, 17,  1],
       [ 6,  9,  8,  0,  8],
       [ 1,  0,  2,  3, 17]])

In [ ]:
data[0:3]

array([[ 2, 19, 19,  9, 15],
       [11, 13,  4, 15,  5],
       [ 1,  1, 10, 17,  1]])

In [ ]:
data[0,1]

np.int64(19)

In [ ]:
data[0:3,4:5]

array([[15],
       [ 5],
       [ 1]])

In [ ]:
data[0:4,1:5]

array([[19, 19,  9, 15],
       [13,  4, 15,  5],
       [ 1, 10, 17,  1],
       [ 9,  8,  0,  8]])

In [ ]:
data[-4:-3,-2:-1]

array([[15]])

In [ ]:
data[-4:-2,-3:-2]

array([[ 4],
       [10]])

In [ ]:
data[0,:]

array([ 2, 19, 19,  9, 15])

In [ ]:
data[:,0]

array([ 2, 11,  1,  6,  1])

In [ ]:
data.shape

(5, 5)

In [ ]:
data.size

25

In [ ]:
data.T

array([[ 2, 11,  1,  6,  1],
       [19, 13,  1,  9,  0],
       [19,  4, 10,  8,  2],
       [ 9, 15, 17,  0,  3],
       [15,  5,  1,  8, 17]])

In [ ]:
data

array([[ 2, 19, 19,  9, 15],
       [11, 13,  4, 15,  5],
       [ 1,  1, 10, 17,  1],
       [ 6,  9,  8,  0,  8],
       [ 1,  0,  2,  3, 17]])

In [ ]:
 x=2

In [ ]:
data*2

array([[ 4, 38, 38, 18, 30],
       [22, 26,  8, 30, 10],
       [ 2,  2, 20, 34,  2],
       [12, 18, 16,  0, 16],
       [ 2,  0,  4,  6, 34]])

In [ ]:
data**2

array([[  4, 361, 361,  81, 225],
       [121, 169,  16, 225,  25],
       [  1,   1, 100, 289,   1],
       [ 36,  81,  64,   0,  64],
       [  1,   0,   4,   9, 289]])

In [ ]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,3))

In [ ]:
x

array([[6, 4, 5],
       [2, 0, 2],
       [2, 5, 0]])

In [ ]:
y

array([[6, 5, 6],
       [8, 6, 9],
       [1, 7, 1]])

In [ ]:
np.add(x,2)

array([[8, 6, 7],
       [4, 2, 4],
       [4, 7, 2]])

In [ ]:
np.multiply(x,2)

array([[12,  8, 10],
       [ 4,  0,  4],
       [ 4, 10,  0]])

In [ ]:
np.multiply(x,4)

array([[24, 16, 20],
       [ 8,  0,  8],
       [ 8, 20,  0]])

In [ ]:
np.divide(x,2)

array([[3. , 2. , 2.5],
       [1. , 0. , 1. ],
       [1. , 2.5, 0. ]])

In [ ]:
np.floor_divide(x,2)

array([[3, 2, 2],
       [1, 0, 1],
       [1, 2, 0]])

In [ ]:
np.exp(x)

array([[403.42879349,  54.59815003, 148.4131591 ],
       [  7.3890561 ,   1.        ,   7.3890561 ],
       [  7.3890561 , 148.4131591 ,   1.        ]])

In [ ]:
np.pow(x,2)

array([[36, 16, 25],
       [ 4,  0,  4],
       [ 4, 25,  0]])

In [ ]:
np.random.rand(5,5)

array([[0.13365604, 0.0953532 , 0.86453928, 0.32209384, 0.46208148],
       [0.91312943, 0.23266533, 0.69760119, 0.52860043, 0.1531952 ],
       [0.79814463, 0.50835465, 0.5126988 , 0.87800975, 0.15297344],
       [0.84646312, 0.41196609, 0.49325984, 0.03397969, 0.26504484],
       [0.19023242, 0.03365103, 0.42988545, 0.46518581, 0.22756156]])

In [ ]:
np.random.randn(1000,1000).std()

np.float64(0.9999026970873445)

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
data=np.random.randint(0,10,(5,5))

In [ ]:
data

array([[4, 2, 9, 1, 3],
       [8, 5, 3, 6, 8],
       [5, 8, 1, 6, 9],
       [1, 2, 5, 4, 1],
       [6, 3, 0, 2, 1]])

In [ ]:
print(data.sum())
print(data.max())
print(data.min())

103
9
0


In [ ]:
data.argmax()

np.int64(2)

In [ ]:
data=np.random.randint(0,10,(3,3))

In [ ]:
data

array([[2, 0, 1],
       [0, 7, 4],
       [7, 5, 2]])

In [ ]:
data.sum(axis=1)

array([ 3, 11, 14])

In [ ]:
data.sum(axis=0)

array([ 9, 12,  7])

In [ ]:
data

array([[2, 0, 1],
       [0, 7, 4],
       [7, 5, 2]])

In [ ]:
data.argmin(axis=1)

array([1, 0, 2])

In [ ]:
data.argmin(axis=0)

array([1, 0, 0])

In [ ]:
data.max(axis=0)

array([7, 7, 4])