In [1]:
import numpy as np

In [2]:
data=np.random.randint(0,10,(3,3))


In [3]:
data


array([[0, 6, 1],
       [8, 0, 2],
       [0, 3, 0]])

In [4]:
data.sum()

np.int64(20)

In [5]:
data.sum(axis=0)

array([8, 9, 3])

In [6]:
data.sum(axis=1)

array([ 7, 10,  3])

In [7]:
data.max()

np.int64(8)

In [8]:
data.min()

np.int64(0)

In [9]:
data

array([[0, 6, 1],
       [8, 0, 2],
       [0, 3, 0]])

In [10]:
data.argmax(axis=0)

array([1, 0, 1])

In [11]:
data.argmax()

np.int64(3)

In [12]:
data.argmin()

np.int64(0)

In [13]:
data.argmin().sum()

np.int64(0)

In [14]:
data

array([[0, 6, 1],
       [8, 0, 2],
       [0, 3, 0]])

In [15]:
data.argmax(axis=1)

array([1, 0, 1])

In [16]:
data.argmax(axis=0)

array([1, 0, 1])

In [17]:
data=np.random.randint(0,100,(10,5))

In [18]:
data ###10 stokes,total 5 products sales

array([[89, 21, 73,  2, 35],
       [95, 34, 36, 93, 52],
       [32, 97, 91, 64, 76],
       [ 5, 53, 34, 45, 61],
       [ 1, 55, 46, 65, 53],
       [57, 63, 68, 95,  4],
       [13, 77, 98, 28, 82],
       [18, 75, 89,  5, 83],
       [82, 96, 14, 65, 82],
       [59, 66, 77, 81, 22]])

In [19]:
data.sum()

np.int64(2807)

In [20]:
data.sum(axis=1)

array([220, 310, 360, 198, 220, 287, 298, 270, 339, 305])

In [21]:
data.sum(axis=0)

array([451, 637, 626, 543, 550])

In [22]:
data.sum(axis=1).argmin()+1

np.int64(4)

In [23]:
data

array([[89, 21, 73,  2, 35],
       [95, 34, 36, 93, 52],
       [32, 97, 91, 64, 76],
       [ 5, 53, 34, 45, 61],
       [ 1, 55, 46, 65, 53],
       [57, 63, 68, 95,  4],
       [13, 77, 98, 28, 82],
       [18, 75, 89,  5, 83],
       [82, 96, 14, 65, 82],
       [59, 66, 77, 81, 22]])

In [24]:
data.sum(axis=1).argmax()+1

np.int64(3)

In [25]:
data.sum(axis=0).argmin()+1

np.int64(1)

In [26]:
data.sum(axis=0).argmax()

np.int64(1)

In [27]:
data.sum(axis=0)

array([451, 637, 626, 543, 550])

In [28]:
data.sum(axis=0).argmax()+1

np.int64(2)

In [29]:
data.sum(axis=0).argmin()+1

np.int64(1)

In [30]:
data

array([[89, 21, 73,  2, 35],
       [95, 34, 36, 93, 52],
       [32, 97, 91, 64, 76],
       [ 5, 53, 34, 45, 61],
       [ 1, 55, 46, 65, 53],
       [57, 63, 68, 95,  4],
       [13, 77, 98, 28, 82],
       [18, 75, 89,  5, 83],
       [82, 96, 14, 65, 82],
       [59, 66, 77, 81, 22]])

In [31]:
data.sum(axis=0).max()

np.int64(637)

In [32]:
data.sum(axis=0).min()

np.int64(451)

In [33]:
data.sum(axis=0).max()-data.sum(axis=0).min()

np.int64(186)

In [34]:
data=np.random.randint(0,10,0)

In [35]:
data

array([], dtype=int64)

In [36]:
data=np.random.randint(0,10,10)

In [37]:
data.mean()

np.float64(4.9)

In [38]:
data

array([7, 3, 4, 0, 8, 8, 0, 3, 9, 7])

In [39]:
np.median(data)

np.float64(5.5)

In [40]:
data

array([7, 3, 4, 0, 8, 8, 0, 3, 9, 7])

In [41]:
np.quantile(data,0.25)

np.float64(3.0)

In [42]:
np.quantile(data,0.75)

np.float64(7.75)

In [43]:
np.quantile(data,0.50)

np.float64(5.5)

In [44]:
data

array([7, 3, 4, 0, 8, 8, 0, 3, 9, 7])

In [45]:
np.median(data)

np.float64(5.5)

In [46]:
### descripitive statistics
mean
median
max
min
range
q1
q3
iqr
std
var

NameError: name 'mean' is not defined

In [53]:
data

array([7, 3, 4, 0, 8, 8, 0, 3, 9, 7])

In [47]:
np.std(data)

np.float64(3.176476034853718)

In [51]:
np.var(data)

np.float64(10.09)

In [54]:
data=np.random.randint(0,10,(10,2))

In [55]:
np.corrcoef(data.T)

array([[ 1.        , -0.13994079],
       [-0.13994079,  1.        ]])

In [58]:
v1=np.arange(1,11)
v2=np.arange(10,20)

In [59]:
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [64]:
x=[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
x.reverse()
v2=np.array(x)
v2

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [69]:
data[:,1]=v1
data[:,0]=v2

In [70]:
np.corrcoef(data.T)

array([[ 1., -1.],
       [-1.,  1.]])

In [70]:
data=np.random.randint(0,10,(5,5))

In [71]:
np.corrcoef(data)

/usr/local/lib/python3.11/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.11/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])